/**
 * Email template generation for feedback notifications
 */

interface EmailData {
  studentName: string;
  studentEmail: string;
  essayTitle: string;
  overallScore: number;
  strengths: string[];
  improvements: string[];
  grammarIssues: string[];
  suggestedFeedback: string;
  teacherName?: string;
}

/**
 * Generate HTML email template for feedback notification
 */
export function generateFeedbackEmail(data: EmailData): string {
  const {
    studentName,
    essayTitle,
    overallScore,
    strengths,
    improvements,
    grammarIssues,
    suggestedFeedback,
    teacherName = 'Your Teacher',
  } = data;

  const scoreColor = overallScore >= 80 ? '#10b981' : overallScore >= 60 ? '#f59e0b' : '#ef4444';

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Essay Feedback</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .container {
      background-color: white;
      border-radius: 8px;
      padding: 30px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #3b82f6;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      color: #1f2937;
      margin: 0;
      font-size: 28px;
    }
    .score-badge {
      display: inline-block;
      background-color: ${scoreColor};
      color: white;
      font-size: 36px;
      font-weight: bold;
      padding: 15px 30px;
      border-radius: 8px;
      margin: 20px 0;
    }
    .section {
      margin-bottom: 25px;
    }
    .section h2 {
      color: #1f2937;
      font-size: 20px;
      margin-bottom: 10px;
      border-left: 4px solid #3b82f6;
      padding-left: 12px;
    }
    .section ul {
      list-style: none;
      padding: 0;
    }
    .section li {
      padding: 8px 0;
      padding-left: 20px;
      position: relative;
    }
    .section li:before {
      content: "•";
      position: absolute;
      left: 0;
      color: #3b82f6;
      font-weight: bold;
    }
    .feedback-text {
      background-color: #f9fafb;
      border-left: 4px solid #3b82f6;
      padding: 15px;
      border-radius: 4px;
      margin-top: 10px;
      white-space: pre-wrap;
    }
    .footer {
      text-align: center;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      color: #6b7280;
      font-size: 14px;
    }
    .essay-title {
      background-color: #eff6ff;
      padding: 12px;
      border-radius: 6px;
      font-weight: 600;
      color: #1e40af;
      margin-bottom: 20px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📝 Essay Feedback</h1>
      <p style="color: #6b7280; margin: 10px 0 0 0;">Hi ${studentName},</p>
    </div>

    <div class="essay-title">
      Essay: ${essayTitle}
    </div>

    <div style="text-align: center;">
      <div class="score-badge">${overallScore}/100</div>
    </div>

    ${strengths.length > 0 ? `
    <div class="section">
      <h2>✨ Strengths</h2>
      <ul>
        ${strengths.map(s => `<li>${s}</li>`).join('')}
      </ul>
    </div>
    ` : ''}

    ${improvements.length > 0 ? `
    <div class="section">
      <h2>💡 Areas for Improvement</h2>
      <ul>
        ${improvements.map(i => `<li>${i}</li>`).join('')}
      </ul>
    </div>
    ` : ''}

    ${grammarIssues.length > 0 ? `
    <div class="section">
      <h2>✏️ Grammar & Style Notes</h2>
      <ul>
        ${grammarIssues.map(g => `<li>${g}</li>`).join('')}
      </ul>
    </div>
    ` : ''}

    <div class="section">
      <h2>💬 Detailed Feedback</h2>
      <div class="feedback-text">${suggestedFeedback}</div>
    </div>

    <div class="footer">
      <p><strong>Keep up the great work!</strong></p>
      <p>If you have any questions about this feedback, please reach out to ${teacherName}.</p>
      <p style="margin-top: 20px; font-size: 12px; color: #9ca3af;">
        This email was generated by MarkMate - AI-Powered Essay Grading
      </p>
    </div>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Generate plain text version of feedback email
 */
export function generateFeedbackEmailPlainText(data: EmailData): string {
  const {
    studentName,
    essayTitle,
    overallScore,
    strengths,
    improvements,
    grammarIssues,
    suggestedFeedback,
    teacherName = 'Your Teacher',
  } = data;

  return `
ESSAY FEEDBACK
==============

Hi ${studentName},

Essay: ${essayTitle}
Overall Score: ${overallScore}/100

${strengths.length > 0 ? `
STRENGTHS:
${strengths.map(s => `• ${s}`).join('\n')}
` : ''}

${improvements.length > 0 ? `
AREAS FOR IMPROVEMENT:
${improvements.map(i => `• ${i}`).join('\n')}
` : ''}

${grammarIssues.length > 0 ? `
GRAMMAR & STYLE NOTES:
${grammarIssues.map(g => `• ${g}`).join('\n')}
` : ''}

DETAILED FEEDBACK:
${suggestedFeedback}

Keep up the great work!

If you have any questions about this feedback, please reach out to ${teacherName}.

---
This email was generated by MarkMate - AI-Powered Essay Grading
  `.trim();
}

/**
 * Mock email sending function (to be replaced with actual email service)
 * In production, this would call a Supabase Edge Function or third-party email service
 */
export async function sendFeedbackEmail(
  emailData: EmailData
): Promise<{ success: boolean; error?: string }> {
  try {
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 1000));

    // In production, you would:
    // 1. Call Supabase Edge Function
    // 2. Use SendGrid, AWS SES, Resend, or similar service
    // 3. Store notification history in database

    console.log('📧 Mock email sent:', {
      to: emailData.studentEmail,
      subject: `Feedback for "${emailData.essayTitle}"`,
      html: generateFeedbackEmail(emailData),
      text: generateFeedbackEmailPlainText(emailData),
    });

    // Mock successful send
    return { success: true };
  } catch (error: any) {
    console.error('Email send error:', error);
    return {
      success: false,
      error: error.message || 'Failed to send email',
    };
  }
}
